name: Run Selenium TestNG Tests with Maven and Allure
run-name: ${{ github.actor }} is running Selenium TestNG tests with Maven and Allure 🚀
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code #to get the right sourse code from repository
        uses: actions/checkout@v4

      - name: Set up JDK 17 #need to match with pom.xml
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 📦 Cache Maven Dependencies #reduce cache time
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.9

      - name: Clean old Allure results
        run: |
          rm -rf allure-results
          rm -rf target/site/allure-maven-plugin

      - name: Run TestNG Tests with Maven
        run: mvn clean test -Dsurefire.useFile=false --batch-mode # Chạy test bằng Maven, log hiển thị rõ hơn
      # Sử dụng `mvn clean test` thay vì `mvn clean install` để chỉ chạy test mà không đóng gói JAR,
      # đảm bảo chạy đúng `runAllTestcases.xml` (nếu đã cấu hình trong `maven-surefire-plugin`).
      # batch mode: Giảm log không cần thiết, sạch và nhanh hơn, neu muon debug thi bo batchmode

      - name: 📊 Generate Allure Report
        if: always()
        run: |
          mvn allure:report -q
          
      - name: ☁️ Upload Allure HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/

      - name: 📄 Upload Raw Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/

      - name: 🌐 Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3 # Deploy báo cáo Allure lên GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven-plugin/
          #publish_branch: gh-pages

      - name: 🔗 Print Allure Report URL
        if: always()
        run: |
          echo "🔗 Allure Report is available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"